### ISSUE TITLE
Current build on travis-ci fails

### ISSUE THREAD

**Issue by lo1tuma** [eslint/eslint-tester#16]
See: https://travis-ci.org/eslint/eslint-tester/builds

**Comment by nzakas** [comment]
Should be fine now. There's a weird dependency cycle here where adding a new feature to the tester and to eslint causes this. The tester uses ESLint as part of its tests, so I can test locally but the published version will fail because it's not updated yet. We could alter the Travis script to check out the eslint master branch to avoid this, but it doesn't happen very frequently.

**Comment by lo1tuma** [comment]
Ah yes, I remember the discussion about this. I re-run the build on travis, now it is green again.
