### ISSUE TITLE
eslint, is-my-json-valid should be dependencies

### ISSUE THREAD

**Issue by zpao** [eslint/eslint-tester#22]
As of #21, these should be dependencies, not devDependencies.

cc @PiPeep.

**Comment by gyandeeps** [comment]
Good catch. 
We will take a look at it.

**Comment by zpao** [comment]
eslint might be best as a peerDep (you presumably wouldn't be testing an eslint rule without eslint already installed) but then you'd also want it as a devDep. Up to you, I've only spent a whole 3 seconds thinking about it :)

**Comment by PiPeep** [comment]
To add to what @zpao said, in #21, there appears to be a line saying:

```js
...
validator = require("eslint").validator,
...
```

However, [`ESLintTester` is already be passed `eslint.linter`](https://github.com/eslint/eslint-tester/blob/18d2a86dd45c67ebc7fb184a365229b6377e8ffb/tests/lib/eslint-tester.js#L54). IMHO, either it should be able to pick validator out from `eslint.linter`, or require we pass `eslint` instead of `eslint.linter`.

Right now, it's possible that eslint-tester might end up with two different versions of eslint, and cause some strange issues.

**Comment by btmills** [comment]
> either it should be able to pick validator out from eslint.linter, or require we pass eslint instead of eslint.linter

Agreed. Unfortunately, due to the complicated relationship between eslint and eslint-tester, either option will mean handling two concurrent releases again. @nzakas or @ilyavolodin - thoughts?

**Option 1:** Export `validator` from `lib/eslint`, and it no longer needs to be exported from `lib/api`.

**Option 2:** Rules should pass `lib/api`, not `lib/eslint` to eslint-tester.

Architecturally, I think it's more proper that eslint-tester would use the public API (so option 2), but that would require changing *every single rule*, and we can't suddenly break third-party plugin rules, meaning we might have to go with option 1.

**Comment by gyandeeps** [comment]
I think we should create a separate issue to track this.

**Comment by nzakas** [comment]
Agreed, let's split out this discussion into a separate issue and leave this one to manage the dependency listings.

I do think ESLint should be a peer dependency - it's probably not already because I was a node neophyte when the tester was first split into its own module.

**Comment by btmills** [comment]
Split to #24.
